# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Lab2_TemplateApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lab2_TemplateApp
  pod 'NotificationBannerSwift'
  pod 'Alamofire', '~> 5.0.0.beta.1'
end


#[!] Please close any current Xcode sessions and use `Lab2_TemplateApp.xcworkspace` for this project from now on.